### ISSUE TITLE
Frequency of single mutations appears to be out of all variants: plotMutFreqs

### ISSUE THREAD

**Issue by caelanradford** [jbloomlab/dms_tools2#12]
CodonVariantTable.plotMutFreqs appears to plot the frequency of single amino acid mutations out of all variants at each site, rather than just the frequency of single amino acid mutations at each site. 

![image](https://user-images.githubusercontent.com/32181278/51873019-5d1ad800-2310-11e9-8de0-749495f32e7d.png)

**Comment by jbloom** [comment]
There was indeed a bug, it is fixed in commit 5f2caa7cd8b and version tag 2.4.3.

**Comment by jbloom** [comment]
@caelanradford: But do re-run on your notebook to confirm. I would expect frequency of single-mutant variants to increase to in fact slightly increase with average mutation rate as there will be more single-mutant variants relative to wildtype (these plots include single mutants **and** wildtype).
