### ISSUE TITLE
mask site in `dms2_bcsubamp`

### ISSUE THREAD

**Issue by Haddox** [jbloomlab/dms_tools2#2]
It might be nice if you could mask certain sites when running `dms2_bcsubamp`. In my case, there are regions of env I didn't mutagenize. I need to align to the full-length gene so that sites are numbered appropriately, but this skews plots showing gene-wide mutation sampling and frequency. Masking these unmutated regions could solve this problem, while allowing you to retain the correct numbering scheme.

**Comment by jbloom** [comment]
Added in this commit:
https://github.com/jbloomlab/dms_tools2/commit/0537a9de8bb35a12cf8c00339a5783f3e26e8ccd

The new option is `--sitemask` to `dms2_bcsubamp` / `dms2_batch_bcsubamp`.
