### ISSUE TITLE
sites not ordered correctly in `dms2_batch_prefs` average preferences file

### ISSUE THREAD

**Issue by Haddox** [jbloomlab/dms_tools2#3]
I used `dms2_batch_prefs` to infer Env's preferences. The CSV file for the individual replicates look good. But, the CSV file for the averaged preferences has a small problem: the sites are not in the correct order. They appear to be ordered as if they were sorted as strings. E.g., whereas the file should start with (31, 32, ...) and end with (..., 701, 702), it instead starts with (100, 101, ...) and ends with (..., 98, 99).

This problem does not seem critical since the data is all there. But like it might be worth fixing from an aesthetic standpoint? Is there an easy fix? It gets a bit complicated since some of my sites are not in the HXB2 reference strain and so are numbered things like '184a'. So simply sorting the sites as integers would not be an option.

**Comment by jbloom** [comment]
Fixed in this commit:
https://github.com/jbloomlab/dms_tools2/commit/4a2f864b1b7cca44079d004be590a31a43a985cc
