### ISSUE TITLE
Add chartype = nucleotide to dms2_bcsubamp

### ISSUE THREAD

**Issue by adingens** [jbloomlab/dms_tools2#32]
It would be process some bcsubamp sequencing data according to nucleotide rather than codon (for example, when using bcsubamp sequencing to analyze apobec hypermutation). Alternatively, we could add a codon counts to nucleotide counts function.

**Comment by jbloom** [comment]
@adingens: How important is the parsing of linked reads? I think we could easily add the ability to report nucleotide counts, but that will *not* deal with the linked reads issue. If the latter is important, maybe we should make a solution that does both immediately. If the nucleotide counts are more important, we can just do that.

**Comment by jbloom** [comment]
@adingens: This is now implemented in version 2.6.1.

See `utils.codon_to_nt_counts`:
https://jbloomlab.github.io/dms_tools2/dms_tools2.utils.html#dms_tools2.utils.codon_to_nt_counts
