### ISSUE TITLE
Errors running examples

### ISSUE THREAD

**Issue by lconde-ucl** [jbloomlab/dms_tools2#45]
Dear Jesse,

I'm trying to run all the examples and I keep having issues with most of them. I wanted to try all the examples to iunderstand dms_tools2 before I try it on my data. I can run the jupyter notebooks successfully for Doud16 and Dou17, but all the other examples terminate with errors and I was wondering if you could help? 

Both Dingens2017 and Dingens2018 terminate with the following error:
```
RRuntimeError: Error in guessSeqType(rownames(seqs)) : 
  Could not get guess seq_type. Please explicitly define sequence type or use "other" with custom namespaces.
Calls: <Anonymous> ... geom_logo -> lapply -> FUN -> logo_data -> guessSeqType
```

Lee2018 terminates with this error:
`FileNotFoundError: [Errno 2] No such file or directory: './results/phydms_analysis//human_ExpCM_summary_avgprefs_modelparams.txt'
`

For Doud18:
`error: bad escape \m at position 2`

And for Haddox2018:
`AttributeError: module 'rpy2.rinterface' has no attribute 'R_VERSION_BUILD'`

I'm attaching a text file that shows all the complete tracebacks. 
I apologise in advance if these are trivial errors that should be easy to solve, I am not a python person so it's out of my comfort zone!

Best regards
Lucia

[dms_tools2_example_errors.txt](https://github.com/jbloomlab/dms_tools2/files/4481254/dms_tools2_example_errors.txt)

**Comment by jbloom** [comment]
Hi Lucia,

Unfortunately most of these look like installation / computing environment issues, and those are typically sufficiently complex that I'm not able to troubleshoot them on other lab's servers. We are moving towards trying to do future analyses in `conda` environments so the whole computing environment can be re-created, but unfortunately we didn't do this for those earlier analyses.

For all except the Lee2108 error, these appear to be problems with using `rp2y` to run the `rplot` module to make logo plots. We have now moved towards using [dmslogo](https://jbloomlab.github.io/dmslogo/), which is a purely Python package and avoids the issues created with using `rpy2` to run `R` in Python (which tends to be susceptible to installation problems). If it works for the goal of your analyses, you might just remove the chunks of code that are using the `rplot` module to make logo plots, or plot them in some other way?

For the Lee2018 `phydms` error, probably `phydms` isn't running. Look at the `*.log` files in `./results/phydms_analysis/` to see if you can figure out why. For instance, maybe `phydms` or `RAxML` aren't installed?

Finally, if you just want to access specific data or results files, let me know and I can share them from runs on our computing server, which has an environment in which all of these run.

I'm closing this issue, but feel free to re-open (or just post without re-opening if you simply want me to send files).

**Comment by lconde-ucl** [comment]
Hi Jesse,
many thanks for your prompt reply. Thanks for offering to share the results but it's not really necessary, I just wanted to run the examples to make sure dms_tools2 was running OK before using it with our data, so I don't really need to get any specific results file.
Many thanks for the tips, I will take the advice and use dmslogo instead of rplot for logo plots. As for Lee2018, phydms is installed (v2.3.8), but you are right that RAxML is not, so that's probably the issue.
Thanks for your help,
Regards,
Lucia
