### ISSUE TITLE
logoplots made using `dms2_logoplot` are missing legends for overlays

### ISSUE THREAD

**Issue by Haddox** [jbloomlab/dms_tools2#5]
I just added overlays to my logo plots for Env. However, they are missing the legend that describes each overlay by telling you what each color means. For instance, here's an example of one I just generated:

![image](https://user-images.githubusercontent.com/4372993/31915470-979b283c-b81c-11e7-8213-09b24aec8759.png)

**Comment by Haddox** [comment]
My code for generating this plot is in the bottom cell of notebook: `computational_notebooks/hhaddox/2017/compare_Env_mutational_tolerance_dms_tools2/BG505_DMS.ipynb` and is pasted below:

# Make the logo plot        
log = !dms2_logoplot \
        --prefs {avgprefs} \
        --name {logoname} \
        --outdir {prefsdir} \
        --overlay1 {wtoverlayfile} wildtype wildtype \
        --overlay2 {regionoverlayfile} R Region \
        --nperline 68 \
        --use_existing {use_existing}

**Comment by jbloom** [comment]
@Haddox: do you have the most recent version of phydms installed?

**Comment by Haddox** [comment]
@jbloom: Yes, I'm at least current with the most recent version you can install via `pip`:

>>>phydms --version
phydms 2.1.3

Just to make sure, I upgraded `phydms` using `pip`, relaunched the notebook, and remade the logo plot. Unfortunately, I ran into the same issue. Do you think it has something to do with `phydms`?

**Comment by jbloom** [comment]
Can you post a ZIP file with input and command to reproduce error.

**Comment by Haddox** [comment]
Here is a ZIP file with a Jupyter notebook and input files that reproduces the error.

[troubleshooting_logo_plot_problem.zip](https://github.com/jbloomlab/dms_tools2/files/1415062/troubleshooting_logo_plot_problem.zip)

**Comment by jbloom** [comment]
The issue should now be resolved.

**Comment by jbloom** [comment]
Note that the actual bug was in `phydms`, so you need version 2.1.4 of that. The `setup.py` for `dms_tools2` now requires that.
