### ISSUE TITLE
Analysis with single-Read data

### ISSUE THREAD

**Issue by euphowayne78** [jbloomlab/dms_tools2#54]
Hi,

I am trying to analyze my single-read library with dms2_bcsubamp using the following command by either leaving out a value for R2START or by setting it to 0,

dms2_bcsubamp \
--outdir /Users/wee/HTS/Zip/Results/Minus1/ \
--name Minus1 \
--use_existing no \
--refseq /Users/wee/HTS/Zip/Template/Fidelity.fasta \
--alignspecs 1,93,17,0 \
--bclen 14 \
--fastqdir /Users/wee/HTS/Zip/HTStream/Minus1/ \
--R1 Minus1.htstream_SE.fastq

and of course I got back an error message saying that R2START must be >=1. I am wondering if there is a way around this to enable single-read analysis?

**Comment by jbloom** [comment]
Unfortunately the code isn't really set up to enable this right now. It might be possible to modify to enable it, but I don't anticipate having time to do that soon.

**Comment by euphowayne78** [comment]
Got it. Thanks Jesse!
