### ISSUE TITLE
Issue with fastq-dump version string

### ISSUE THREAD

**Issue by FlyinTeller** [jbloomlab/dms_tools2#61]
There is an issue with the version string from `fastq-dump`, at least in sratoolkit 2.11. The output of `fastq-dump --version` does not seem to contain a `:`

```
sratoolkit.2.11.0-ubuntu64/bin/fastq-dump --version

"sratoolkit.2.11.0-ubuntu64/bin/fastq-dump" version 2.11.0
```

This breaks the logic in `sra.py` for the version check

This has also been reported [here](https://stackoverflow.com/questions/70848105/error-wont-dissapear-even-when-deleting-commenting-the-faulty-lines)

**Comment by jbloom** [comment]
The updated version is now on PyPI as 2.6.11.

**Comment by FlyinTeller** [comment]
Thanks, I have added that info to the SO post so users with a similar issue will find this information
