### ISSUE TITLE
One sample and only 1 barcode (single-end run)?

### ISSUE THREAD

**Issue by RicardoBiol** [jbloomlab/dms_tools2#63]
Hello, I have a quick question regarding using dms2_bcsubamp or dms2_batch_bcsubamp. Is it possible to run this code on sequencing data from a single-end run instead of a paired-end run? Also for only one subamplicon instead of multiple ones. The way I'm trying to set this up is to use the same NGS strategy as explained in:

https://jbloomlab.github.io/dms_tools2/bcsubamp.html

Except I use FASTQs from a single-end run instead of a paired-end run. I can optionally still amplify the target by appending 2 barcodes on each site, making it small enough so that a single-end read captures both barcodes. The only issue is the resulting FASTQs will be R1 instead of both R1 & R2.

Is there an easy way to do this or am I missing something that would make this impossible? My idea was to inverse-complement R1 FASTQs and treat them like R2 FASTQs and try running the script that way.

**Comment by jbloom** [comment]
Those programs are designed for paired end, so maybe not. It may be better to write a custom script to handle this.

But it's possible that you could do the reverse-complementing thing you propose if you wanted to somewhat abuse the intended use of the program: I'm not sure if that would work or not.
