### ISSUE TITLE
weblogo plot image artifacts.

### ISSUE THREAD

**Issue by adalisan** [jbloomlab/dms_tools2#64]
The pdf  plots for differential selections that are generated sometime have weird lines instead of letters. I  thought  these are just squashed letters, but they sometimes are drawn across multiple sites. Despite increasing the letterheight these lines are persisting. Is this an artifact of matplotlib  and pdf creation>

**Comment by jbloom** [comment]
Hmm, without a more detailed example I can't really answer this.

**Comment by adalisan** [comment]
![nsp12_0 (2)](https://user-images.githubusercontent.com/1790714/158625401-02f5a5fa-9085-42b6-8486-e6d03cd8cf2e.png)

So I took a cropped screenshot of the output of the pdf. this is one of the many lines that have artifacts like this. They look like very squashed versions of some letters. But when they do  appear, they are spread across multiple positions which does not make sense to me.

**Comment by jbloom** [comment]
That's strange. Not sure what is causing that. Honestly, I'd suggest switching to https://jbloomlab.github.io/dmslogo/ or https://logomaker.readthedocs.io/en/latest/ instead as I'm not really maintaining the logo plots for `dms_tools2` anymore beyond making sure it still works on our particular sertup.

**Comment by jbloom** [comment]
The `dmslogo` documentation has some examples: https://jbloomlab.github.io/dmslogo/

Also, here is some example code from one of our projects: https://github.com/jbloomlab/SARS-CoV-2-RBD_MAP_LY-CoV555/blob/main/escape_profiles.ipynb
