### ISSUE TITLE
Compiling errors for newer Mac OS (Xcode commandline tools)

### ISSUE THREAD

**Issue by RicardoBiol** [jbloomlab/dms_tools2#65]
I started getting compilation errors when trying to install/update dms_tools2 right after I performed Apple’s software update (upgrade to Monterey):

`command 'x86_64-apple-darwin13.4.0-clang++' failed with exit status 1`

There might be something wrong with the xcode commandline tools.

It might be a good idea to check the clang version requirements or update them to require x86_64-apple-darwin21.4.0

**Comment by jbloom** [comment]
Unfortunately I think this problem has to do with software installation of the C compiler on your Mac, and is beyond the scope of what I can troubleshoot.
