### ISSUE TITLE
Request to allow different length barcodes (including 0 length) 

### ISSUE THREAD

**Issue by AtanasDRadkov** [jbloomlab/dms_tools2#7]
Hello, 
This is Atanas from Chou lab. I emailed Jesse and he asked me to start an issue here. Please see below for my email:

We have prepared and sequenced our library in a different way compared to what is described here https://jbloomlab.github.io/dms_tools2/bcsubamp.html. We have one barcode (15 nucleotides) on one end of the amplicon and we have sequenced the entire amplicon with two custom primers (the amplicon is 512bp and I used the v3 600 kit so I went 324 cycles read1 and 301 cycles read2; we are not doing an index read at this point because it is just one sample). My understanding of dms2_tools is that it needs two barcodes on each end (based on the description of the --bclen argument here https://jbloomlab.github.io/dms_tools2/dms2_bcsubamp.html). Is there a way to customize the software in order to run with our data?

Please let me know if this is possible and whether or not it would be too cumbersome to implement. Thank you very much for your time!

**Comment by jbloom** [comment]
@AtanasDRadkov:

This functionality has been added in version `2.2.2`. See the new docs at https://jbloomlab.github.io/dms_tools2/dms2_bcsubamp.html

Basically, if you specify `--bclen2` then it will be interpreted as the length of the barcode on read 2, and `--bclen` will be the length of the barcode on read 1. So depending on which read your barcode is located, your settings should be `--bclen 0 --bclen2 15` or `--bclen 15 --bclen2 0`.

You should be able to upgrade to the latest version with this functionality as described here:
https://jbloomlab.github.io/dms_tools2/installation.html#upgrading-with-pip

The relevant commits are: 75be7db and 5e3849d

I am closing this issue, but feel free to re-open if this doesn't work as expected.
